### ISSUE TITLE
Error Fetching Resource

### ISSUE THREAD

**Issue by jisungbin** [mazassumnida/mazandi#5]
README에 있는 샘플을 포함하여, 일부 API가 작동하지 않습니다.

![image](https://user-images.githubusercontent.com/40740128/147202898-2719713d-9b3c-4b72-96eb-71ac84466969.png)

헤로쿠 배포? 에 문제가 생긴거 같습니다.

![image](https://user-images.githubusercontent.com/40740128/147203007-b8da2750-72c6-4aaa-af8e-2b9b9cf9fa64.png)

**Comment by mori8** [comment]
헤로쿠 무료 dyno를 모두 소진했는데, 제가 지금 컴퓨터를 사용하지 못하는 상황이라 바로 해결하지 못하고 있습니다 😰
내일 중으로 해결하도록 하겠습니다.

**Comment by mori8** [comment]
해결되었습니다 😀
