### ISSUE TITLE
잔디 디자인을 사용해도 괜찮을까요?

### ISSUE THREAD

**Issue by chickenchickenlove** [mazassumnida/mazandi#8]
안녕하세요! 
mazandi를 만들어주셔서 감사합니다.

한 가지 문의 드리고 싶은 것이 있어 이슈를 열었습니다.
다름이 아니라 mazandi에서 만들어 주신 티어 코드를 사용(`SVR`)해도 될까요? 

사용 시, 코드 내의 주석 및 ReadME 페이지에 출처를 밝히고 사용하고자 합니다.
사용 목적은 백준, Github 말고 다른 형태의 잔디심기 프로젝트에 사용하고자 합니다! 

긍정적으로 봐주시면 감사하겠습니다. 🙇

**Comment by mori8** [comment]
안녕하세요! 확인이 너무 늦어서 죄송합니다. 
아직까지 제 코드가 필요하시다면, 사용하셔도 됩니다!
이미 프로젝트가 끝나셨을 것 같아 죄송하네요 😭
